# Generated by Django 4.2.2 on 2023-06-11 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_alter_category_options_userarticlerelation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='readers',
            field=models.ManyToManyField(related_name='relationarticles', through='articles.UserArticleRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userarticlerelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
